logging:
  level:
    com.nace: "debug"

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:NACE;DB_CLOSE_DELAY=-1'
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: caches